#ifndef CONFIG_H
#define CONFIG_H

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 2
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_MAX_SPEED 2
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#endif
